import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Home,Building2,LineChart,ReceiptText,WalletCards,UsersRound,BookOpenCheck,Upload,AlertTriangle,Database,Clock3,RefreshCw,ChevronDown,ChevronRight,X,Landmark,CalendarDays,ShieldCheck,Info,Coins,Target,TrendingUp,BadgeEuro,Search,CheckCircle2}from'lucide-react';
import'bootstrap/dist/css/bootstrap.min.css';import'./style.css';
type State='ok'|'watch'|'alert'|'missing';type Eple={id:string,name:string,states:any,trend:string,freshness:string|null,sources:any,signals:any[],budgetMetrics:any,fdrHistory:any[],pcif?:any};
const eur=(v:any)=>Number(v||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0});const pct=(v:any)=>v==null?'—':`${(Number(v)*100).toFixed(1)} %`;const dateFr=(v:any)=>v?new Date(v).toLocaleDateString('fr-FR'):'—';
const Dot=({s}:{s:State})=><span className={'status-dot '+s}/>;
function App(){const[dash,setDash]=useState<any>(null),[selectedId,setSelectedId]=useState('all'),[view,setView]=useState('Accueil'),[modal,setModal]=useState(false),[result,setResult]=useState<any>(null),[openSignal,setOpenSignal]=useState<string|null>(null),[q,setQ]=useState('');
 const load=()=>fetch('/api/dashboard').then(r=>r.json()).then(setDash);useEffect(load,[]);const all:Eple[]=dash?.establishments||[];const current=selectedId==='all'?null:all.find(e=>e.id===selectedId)||null;const signals=current?.signals||dash?.signals||[];const m=current?.budgetMetrics;const fdr=current?.fdrHistory?.[0];const prev=current?.fdrHistory?.[1];
 const nav=[['Accueil',Home],['Établissements',Building2],['Analyse financière',LineChart],['Budget',ReceiptText],['Dépenses',BadgeEuro],['Recettes',WalletCards],['Trésorerie',Landmark],['Fournisseurs',UsersRound],['Comptabilité générale',BookOpenCheck],['Maîtrise des risques',ShieldCheck]] as const;
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setResult({loading:true});const fd=new FormData(e.currentTarget);const r=await fetch('/api/import/opale',{method:'POST',body:fd});const x=await r.json().catch(()=>({error:`HTTP ${r.status}`}));setResult(x);if(r.ok)load()}
 return <div className="shell"><aside className="sidebar"><div className="logo"><div className="lighthouse">V</div><div><strong>VIGIE EPLE</strong><small>Observer · Analyser · Anticiper</small></div></div><nav>{nav.map(([n,I])=><button className={view===n?'active':''} onClick={()=>setView(n)} key={n}><I size={18}/>{n}</button>)}</nav><div className="side-quote">« Anticiper aujourd'hui<br/>pour sécuriser demain »</div><small className="version">VIGIE v0.0.13</small></aside>
 <main className="content"><header className="topbar"><div className="est-select"><span>Établissement</span><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="all">Vue agence · tous les EPLE</option>{all.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div><div className="situation"><span>Situation au</span><b><CalendarDays size={16}/> {dateFr(current?.freshness||dash?.generatedAt)}</b><small><CheckCircle2 size={14}/> Données historisées</small></div><div className="top-actions"><button onClick={load} className="btn-soft"><RefreshCw size={16}/></button><button onClick={()=>setModal(true)} className="btn-primary-v"><Upload size={16}/> Importer</button></div></header>
 {view==='Accueil'?<HomeView dash={dash} current={current} signals={signals} m={m} fdr={fdr} prev={prev} openSignal={openSignal} setOpenSignal={setOpenSignal}/>:view==='Établissements'?<Establishments all={all} q={q} setQ={setQ} select={(id:string)=>{setSelectedId(id);setView('Accueil')}}/>:<Domain title={view} current={current}/>}</main>
 {modal&&<div className="modalveil" onClick={()=>setModal(false)}><div className="importbox" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(false)}><X/></button><Upload size={28}/><h3>Importer une situation Op@le</h3><p>Balance, budget, CLCA ou FDR. Vigie détecte la source et recalcule le cockpit.</p><form onSubmit={upload}><input name="file" type="file" accept=".lis,.csv" required/><button className="btn-primary-v">Analyser et importer</button></form>{result&&<div className="result">{result.loading?'Analyse en cours…':result.error?`Import refusé : ${result.error}`:`${result.type} · ${result.control?.importedRows||0} lignes importées`}</div>}</div></div>}
 </div>}
function HomeView({dash,current,signals,m,fdr,prev,openSignal,setOpenSignal}:any){if(!dash)return <div className="loading">Construction du cockpit…</div>;const agency=!current;const engagement=m?.engagementRate;const target=m?.trajectoryTarget;const fdrDelta=fdr&&prev?Number(fdr.amount)-Number(prev.amount):null;const trajectory=signals.some((s:any)=>s.level==='alert')?'Action requise':signals.some((s:any)=>s.level==='watch')?'À surveiller':'Trajectoire maîtrisée';return <div className="home fade-in">
 <section className="hero-kpis"><article className={'trajectory '+(trajectory==='Action requise'?'danger':'')}><Target/><span>Trajectoire globale</span><b>{trajectory}</b><small>{agency?'Lecture consolidée de l’agence':current.name}</small></article><Kpi icon={<Coins/>} label={agency?'Budget disponible':'Trésorerie disponible'} value={agency?eur(dash.kpis.totalAvailable):'À connecter'} hint={agency?'Derniers budgets importés':'5151 + placements à intégrer'}/><Kpi icon={<Landmark/>} label="Fonds de roulement" value={fdr?eur(fdr.amount):'—'} hint={fdr?`${fdr.exercise} · ${fdr.is_final?'définitif':'provisoire'}`:'FDR non importé'} delta={fdrDelta}/><Kpi icon={<TrendingUp/>} label="Résultat prévisionnel" value="À construire" hint="Analyse financière permanente"/><Kpi icon={<ReceiptText/>} label="Engagement budgétaire" value={m?pct(engagement):agency&&dash.kpis.totalBudget?pct(dash.kpis.totalCommitted/dash.kpis.totalBudget):'—'} hint={m&&target?`Cible à date ≈ ${pct(target)}`:'Engagé / montant évaluatif'}/></section>
 <section className="main-grid"><article className="panel execution"><div className="panel-title"><div><h3>Exécution budgétaire</h3><p>Engagement réel comparé à la trajectoire EPLE.</p></div><span className="pill">Engagement</span></div><TrajectoryChart rate={m?.engagementRate} target={m?.trajectoryTarget}/>{m?<div className="metric-row"><span><b>{eur(m.budget)}</b> montant évaluatif</span><span><b>{eur(m.committed)}</b> engagé</span><span><b>{eur(m.accounted)}</b> dont réalisé</span><span><b>{eur(m.available)}</b> disponible</span></div>:<p className="muted">Sélectionne un établissement pour détailler sa trajectoire.</p>}</article>
 <article className="panel landing"><div className="panel-title"><div><h3>Trésorerie et atterrissage</h3><p>Constaté, engagé, attendu, estimé.</p></div><Info size={16}/></div><div className="landing-list"><Row n="Solde 5151 disponible" v="À connecter"/><Row n="Placements (CAT)" v="À connecter"/><Row n="Encaissements attendus" v="Subventions à intégrer"/><Row n="Décaissements prévus" v="Contrats à intégrer"/><Row n="Trésorerie projetée au 31/12" v="—" strong/><Row n="FDR projeté" v={fdr?eur(fdr.amount):'—'} strong/></div><button className="detail-link">Voir le calcul détaillé de l'atterrissage <ChevronRight size={15}/></button></article>
 <article className="panel priorities"><div className="panel-title"><div><h3><AlertTriangle size={18}/> Signaux prioritaires</h3><p>{signals.length} signal(s) sur le périmètre.</p></div></div>{signals.slice(0,6).map((s:any,i:number)=><Signal key={`${s.code}-${i}`} s={s} open={openSignal===`${s.code}-${i}`} toggle={()=>setOpenSignal(openSignal===`${s.code}-${i}`?null:`${s.code}-${i}`)}/>)}</article></section>
 <section className="lower-grid"><article className="panel calendar"><div className="panel-title"><div><h3><CalendarDays size={18}/> Calendrier de gestion</h3><p>La trajectoire tient compte du rythme réel d'un EPLE.</p></div></div><div className="months">{['Jan.','Fév.','Mars','Avr.','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'].map(x=><span key={x}>{x}</span>)}</div><div className="phases"><div className="p1">1. Mise en route<small>Exécution calme</small></div><div className="p2">2. Préparation de la rentrée<small>Objectif 75–80 % au 31/08</small></div><div className="summer">Fermeture estivale<small>Activité réduite</small></div><div className="p3">3. Atterrissage<small>Derniers engagements</small></div><div className="closep">Clôture<small>Solde et régularisations</small></div></div></article><PcifCard current={current}/></section>
 </div>}
function Kpi({icon,label,value,hint,delta}:any){return <article className="kpi"><div className="kpi-head">{icon}<span>{label}</span></div><b>{value}</b><small>{hint}</small>{delta!=null&&<em className={delta<0?'down':'up'}>{delta<0?'↓':'↑'} {eur(Math.abs(delta))}</em>}</article>}
function Row({n,v,strong}:any){return <div className={strong?'strong':''}><span>{n}</span><b>{v}</b></div>}
function TrajectoryChart({rate,target}:any){const actual=rate==null?null:Math.max(0,Math.min(1,rate));return <div className="chart"><svg viewBox="0 0 640 220" role="img" aria-label="Trajectoire budgétaire"><g className="gridlines">{[20,60,100,140,180].map(y=><line key={y} x1="45" y1={y} x2="620" y2={y}/>)}</g><polyline className="target" points="45,185 150,170 250,135 350,88 450,60 520,42 620,28"/><polyline className="actual" points={actual==null?'45,185':`45,185 150,172 250,140 350,100 450,${185-actual*150}`}/>{actual!=null&&<><circle className="point" cx="450" cy={185-actual*150} r="6"/><text x="462" y={180-actual*150}>{pct(actual)}</text></>}<text x="520" y="34">cible ≈ {pct(target)}</text></svg><div className="axis"><span>Jan.</span><span>Mars</span><span>Mai</span><span>Juil.</span><span>Sept.</span><span>Nov.</span><span>Déc.</span></div><div className="chartlegend"><i className="dash"/> Trajectoire cible EPLE <i/> Taux d'engagement réel</div></div>}
function Signal({s,open,toggle}:any){return <div className="signal"><button onClick={toggle}><Dot s={s.level}/><div><b>{s.title}</b><small>{s.detail}</small></div><ChevronDown className={open?'rot':''} size={17}/></button>{open&&<div className="why"><strong>Pourquoi ce signal ?</strong>{s.evidence?.map((e:any)=><div key={e.label}><span>{e.label}</span><b>{e.format==='percent'?pct(e.value):typeof e.value==='number'?eur(e.value):String(e.value)}</b></div>)}<p><b>Règle :</b> {s.condition||s.code}</p><p><b>Lecture :</b> {s.interpretation||'Signal à investiguer dans son contexte.'}</p><small>Source : {s.source||s.domain} · règle {s.code}</small></div>}</div>}
function PcifCard({current}:any){const p=current?.pcif;return <article className="panel pcif"><div className="panel-title"><div><h3><ShieldCheck size={18}/> Maîtrise des risques · PCIF</h3><p>Le contrôle interne contextualise les signaux financiers.</p></div></div>{!current?<p className="muted">Sélectionne un établissement pour afficher son contexte PCIF.</p>:p?<><div className="pcif-score"><b>{p.mastery_level!=null?`${Number(p.mastery_level).toFixed(1)}/9`:'—'}</b><span>Niveau de maîtrise déclaré</span></div><div className="pcif-mini"><span><b>{p.major_risks}</b> risques majeurs</span><span><b>{p.open_actions}</b> actions ouvertes</span></div><small>{p.campaign_label||'Campagne PCIF'} · actualisé {dateFr(p.updated_at)}</small></>:<><div className="empty-pcif"><ShieldCheck/><b>Contexte PCIF non connecté</b><span>Vigie est prêt à recevoir une synthèse de campagne : niveau de maîtrise, risques majeurs et actions ouvertes.</span></div></>}</article>}
function Establishments({all,q,setQ,select}:any){const rows=useMemo(()=>all.filter((e:Eple)=>e.name.toLowerCase().includes(q.toLowerCase())),[all,q]);return <div className="page"><div className="pagehead"><div><h2>Établissements</h2><p>Une plateforme, plusieurs EPLE, une lecture homogène.</p></div><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher…"/></div></div><div className="est-cards">{rows.map((e:Eple)=><button key={e.id} onClick={()=>select(e.id)}><Building2/><div><b>{e.name}</b><small>Dernière situation : {dateFr(e.freshness)}</small></div><div className="dots"><Dot s={e.states.budget}/><Dot s={e.states.financial}/><Dot s={e.states.suppliers}/><Dot s={e.states.accounting}/></div><ChevronRight/></button>)}</div></div>}
function Domain({title,current}:any){return <div className="page"><div className="empty-domain"><Database size={34}/><span>VUE MÉTIER</span><h2>{title}</h2><p>{current?`Périmètre : ${current.name}.`:'Vue agence.'} Cette vue utilisera le même moteur explicable que le cockpit, sans dupliquer les données.</p></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
