import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,Landmark,ReceiptText,WalletCards,UsersRound,BookOpenCheck,Upload,AlertTriangle,ChevronRight,Database,Clock3,ArrowUpRight,ArrowDownRight,Minus,Search,X,Building2}from'lucide-react';
import'./style.css';

type State='ok'|'watch'|'alert'|'missing';
type Eple={id:number,name:string,type:string,budget:State,treasury:State,recovery:State,suppliers:State,accounting:State,trend:'up'|'down'|'stable',freshness:string};
const eples:Eple[]=[
{id:1,name:'Collège Jean Moulin',type:'Collège',budget:'ok',treasury:'watch',recovery:'ok',suppliers:'ok',accounting:'ok',trend:'stable',freshness:'18/09/2026'},
{id:2,name:'Collège Pierre Brossolette',type:'Collège',budget:'alert',treasury:'watch',recovery:'alert',suppliers:'ok',accounting:'watch',trend:'down',freshness:'18/09/2026'},
{id:3,name:'LP Sully',type:'LP',budget:'ok',treasury:'ok',recovery:'ok',suppliers:'alert',accounting:'alert',trend:'down',freshness:'17/09/2026'},
{id:4,name:'LPO Rémi Belleau',type:'LPO',budget:'watch',treasury:'ok',recovery:'watch',suppliers:'ok',accounting:'ok',trend:'stable',freshness:'18/09/2026'},
{id:5,name:'Collège Marcel Proust',type:'Collège',budget:'ok',treasury:'ok',recovery:'missing',suppliers:'ok',accounting:'watch',trend:'stable',freshness:'14/06/2026'},
{id:6,name:'Collège Louis Pergaud',type:'Collège',budget:'ok',treasury:'ok',recovery:'ok',suppliers:'watch',accounting:'ok',trend:'up',freshness:'18/09/2026'},
{id:7,name:'Collège Joachim du Bellay',type:'Collège',budget:'watch',treasury:'ok',recovery:'ok',suppliers:'ok',accounting:'ok',trend:'stable',freshness:'16/09/2026'},
{id:8,name:'Collège Alphonse Karr',type:'Collège',budget:'ok',treasury:'ok',recovery:'ok',suppliers:'ok',accounting:'ok',trend:'up',freshness:'18/09/2026'}];
const alerts=[
{id:1,level:'alert' as State,eple:'Collège Pierre Brossolette',domain:'Budget',message:'Projection de dépassement SRH : 18 400 €',detail:'Atterrissage dépenses supérieur aux recettes prévisionnelles.'},
{id:2,level:'alert' as State,eple:'LP Sully',domain:'Comptabilité générale',message:'Compte 4718 : 24 300 € à régulariser',detail:'Solde présent sur 4 situations consécutives · +8 700 € depuis juin.'},
{id:3,level:'watch' as State,eple:'Collège Jean Moulin',domain:'Recouvrement',message:'3 créances > 90 jours : 7 820 €',detail:'Ancienneté maximale : 143 jours.'},
{id:4,level:'watch' as State,eple:'LPO Rémi Belleau',domain:'Fournisseurs',message:'14 factures non payées depuis > 30 jours',detail:'Montant cumulé : 21 640 €.'},
{id:5,level:'missing' as State,eple:'Collège Marcel Proust',domain:'Recouvrement',message:'Données de créances obsolètes',detail:'Dernière situation importée le 14/06/2026.'}];
const labels:Record<State,string>={ok:'Aucun signal détecté',watch:'À examiner',alert:'Action requise',missing:'Données insuffisantes'};
const Dot=({s}:{s:State})=><span className={'dot '+s} title={labels[s]}/>;
function Trend({t}:{t:Eple['trend']}){return t==='down'?<ArrowDownRight className="trend down" size={17}/>:t==='up'?<ArrowUpRight className="trend up" size={17}/>:<Minus className="trend" size={17}/>}
function App(){
 const[section,setSection]=useState('Synthèse'); const[selected,setSelected]=useState<Eple|null>(null); const[query,setQuery]=useState(''); const[importOpen,setImportOpen]=useState(false); const[snapshots,setSnapshots]=useState<any[]>([]); const[importResult,setImportResult]=useState<any>(null);
 useEffect(()=>{fetch('/api/snapshots').then(r=>r.json()).then(x=>setSnapshots(x.snapshots||[])).catch(()=>{})},[]);
 async function importBalance(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setImportResult({loading:true});try{const fd=new FormData(e.currentTarget);const r=await fetch('/api/import/opale',{method:'POST',body:fd});const raw=await r.text();let x:any;try{x=JSON.parse(raw)}catch{x={error:raw||`HTTP ${r.status}`}};if(!r.ok)x={...x,httpStatus:r.status};setImportResult(x);if(r.ok){fetch('/api/snapshots').then(r=>r.json()).then(x=>setSnapshots(x.snapshots||[]))}}catch(err:any){setImportResult({error:`API inaccessible : ${err?.message||err}`})}}
 const filtered=useMemo(()=>eples.filter(e=>e.name.toLowerCase().includes(query.toLowerCase())),[query]);
 const nav=[['Synthèse',LayoutDashboard],['Exécution budgétaire',ReceiptText],['Santé financière',Landmark],['Recouvrement',WalletCards],['Fournisseurs',UsersRound],['Comptabilité générale',BookOpenCheck]] as const;
 return <div className="app"><aside><div className="brand"><div className="brandmark">V</div><div><h1>Vigie</h1><small>EPLE Tools</small></div></div><div className="navlabel">PILOTAGE</div>{nav.map(([x,I])=><button key={x} onClick={()=>setSection(x)} className={section===x?'active':''}><I size={18}/><span>{x}</span></button>)}<div className="asidefoot"><Database size={15}/> Balance Op@le connectée<br/><span>v0.0.9 · Balance + Budget + CLCA</span></div></aside>
 <main><header><div><div className="eyebrow">AGENCE COMPTABLE · EXERCICE 2026</div><h2>{section}</h2><p>Voir l'essentiel. Comprendre le signal. Agir au bon moment.</p></div><div className="headActions"><button className="ghost"><Clock3 size={16}/> Situation au 18/09/2026</button><button className="import" onClick={()=>setImportOpen(true)}><Upload size={17}/> Importer des données</button></div></header>
 {section==='Synthèse'?<><section className="kpis"><article><span>EPLE suivis</span><b>8</b><small>Agence comptable</small></article><article><span>Actions requises</span><b className="red">3</b><small>2 EPLE concernés</small></article><article><span>À examiner</span><b className="amber">7</b><small>5 domaines</small></article><article><span>Trésorerie globale</span><b>2,80 M€</b><small>↗ +3,2 % sur 30 jours</small></article></section>
 <section className="grid"><article className="card radar"><div className="cardhead"><div><h3>Radar de santé par EPLE</h3><p>Un signal n'est pas un diagnostic : cliquez pour investiguer.</p></div><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un EPLE"/></div></div><table><thead><tr><th>Établissement</th><th>Budget</th><th>Trésorerie</th><th>Recouvrement</th><th>Fournisseurs</th><th>Compta géné</th><th>Tendance</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id} onClick={()=>setSelected(e)}><td><b>{e.name}</b><small>{e.type} · données au {e.freshness}</small></td><td><Dot s={e.budget}/></td><td><Dot s={e.treasury}/></td><td><Dot s={e.recovery}/></td><td><Dot s={e.suppliers}/></td><td><Dot s={e.accounting}/></td><td><Trend t={e.trend}/><ChevronRight size={15}/></td></tr>)}</tbody></table><div className="legend"><span><Dot s="alert"/> Action requise</span><span><Dot s="watch"/> À examiner</span><span><Dot s="ok"/> Aucun signal</span><span><Dot s="missing"/> Données insuffisantes</span></div></article>
 <article className="card alerts"><div className="cardhead"><div><h3><AlertTriangle size={19}/> Signaux prioritaires</h3><p>Classés par niveau d'attention.</p></div></div>{alerts.map(a=><button className="alertrow" key={a.id}><Dot s={a.level}/><div><span className="domain">{a.eple} · {a.domain}</span><b>{a.message}</b><p>{a.detail}</p></div><ChevronRight size={16}/></button>)}</article></section>
 <section className="bottomgrid"><article className="card"><div className="cardhead"><div><h3>Exécution budgétaire</h3><p>Réalisé + engagé + reste à faire prévisionnel</p></div><b>76 %</b></div><div className="bar"><i style={{width:'76%'}}/></div><div className="budgetnumbers"><span><b>2,14 M€</b> réalisé</span><span><b>420 k€</b> engagé</span><span><b>310 k€</b> reste à faire</span><span><b>2,87 M€</b> atterrissage</span></div></article><article className="card"><div className="cardhead"><div><h3>Fraîcheur des données</h3><p>Une donnée absente n'est jamais assimilée à zéro.</p></div></div><div className="fresh"><b>7 / 8</b><span>EPLE à jour</span><div className="warning"><Clock3 size={16}/> 1 import de créances à actualiser</div></div></article></section></>:<Domain section={section}/>}</main>
 {selected&&<div className="drawer"><div className="drawerhead"><div><span className="eyebrow">INVESTIGATION</span><h2>{selected.name}</h2><p>Situation au {selected.freshness}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="scoregrid">{[['Budget',selected.budget],['Trésorerie',selected.treasury],['Recouvrement',selected.recovery],['Fournisseurs',selected.suppliers],['Compta générale',selected.accounting]].map(([n,s])=><div><Dot s={s as State}/><b>{n}</b><span>{labels[s as State]}</span></div>)}</div><h3>Signaux détectés</h3>{alerts.filter(a=>a.eple===selected.name).length?alerts.filter(a=>a.eple===selected.name).map(a=><div className="invest"><Dot s={a.level}/><div><b>{a.message}</b><p>{a.detail}</p><button>Examiner le détail <ChevronRight size={14}/></button></div></div>):<div className="noalert">Aucun signal prioritaire détecté sur la dernière situation.</div>}<h3>Traçabilité</h3><div className="trace"><span>Balance</span><b>18/09/2026 · importée</b><span>Budget / exécution</span><b>18/09/2026 · importé</b><span>Achats / engagements</span><b>17/09/2026 · importé</b><span>Créances</span><b>{selected.freshness} · importé</b></div></div>}
 {importOpen&&<div className="modalback" onClick={()=>setImportOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setImportOpen(false)}><X/></button><Upload size={28}/><h2>Importer une situation Op@le</h2><p>Déposez un export Op@le : balance .lis, budget .lis ou CLCA achats .csv. Vigie détecte automatiquement le type, contrôle le fichier et crée un snapshot daté. Le CLCV ventes sera activé dès qu’un export non vide aura permis de valider son mapping.</p><form onSubmit={importBalance}><label>Fichier Op@le<input name="file" type="file" accept=".lis,.csv" required/></label><label>Détection automatique<input disabled value="Balance · Budget · CLCA achats"/></label><button className="import" type="submit">Analyser et importer</button></form>{importResult&&<div className="importresult">{importResult.loading?'Analyse en cours…':importResult.error?<><b>Import refusé : {importResult.error}</b>{importResult.httpStatus&&<p>HTTP {importResult.httpStatus}{importResult.path?` · ${importResult.path}`:''}</p>}</>:<><b>Snapshot créé · {importResult.control.importedRows} lignes importées</b><p>Type détecté : <b>{importResult.type}</b></p>{importResult.alerts&&<><p>{importResult.alerts.length} signal(s) comptable(s) détecté(s).</p>{importResult.alerts.slice(0,5).map((a:any)=><p>• {a.account} — {a.title}</p>)}</>}</>}</div>}<h3>Historique récent</h3>{snapshots.slice(0,5).map((s:any)=><div className="importline"><Database size={17}/><b>{s.establishment_name}</b><span>{String(s.snapshot_date).slice(0,10)} · {s.row_count} lignes</span></div>)}</div></div>}
 </div>}
function Domain({section}:{section:string}){return <div className="domainpage"><div className="placeholder"><Building2 size={36}/><span className="eyebrow">VUE MÉTIER · PROTOTYPE</span><h2>{section}</h2><p>Cette vue sera alimentée par les mêmes snapshots que la synthèse. La v0.0.2 verrouille la navigation et la logique d'investigation avant branchement des importeurs Op@le.</p><div className="fakecards"><div><b>8</b><span>EPLE analysés</span></div><div><b>3</b><span>actions requises</span></div><div><b>7</b><span>points à examiner</span></div></div></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
