import { AlertTriangle, CheckCircle2, ExternalLink, HelpCircle, RefreshCw, ShieldCheck, TrendingDown, TrendingUp } from 'lucide-react';
import { dateFr } from '../lib/format';
import type { Eple } from '../types/dashboard';
export function PcifCard({ current, onSync, syncing=false }: { current:Eple|null; onSync?:(uai:string)=>void; syncing?:boolean }) {
 const p=current?.pcif, answered=Number(p?.answered||0), total=Number(p?.total||0), completion=Number(p?.completion||0);
 const trend=p?.trend==null?null:Number(p.trend), attention=Array.isArray(p?.attention)?p.attention:[];
 const consistency=Array.isArray(p?.consistency)?p.consistency:[], reviews=consistency.filter(x=>x.status==='REVIEW');
 const statusLabel=(s:string)=>s==='REVIEW'?'À examiner':s==='COHERENT'?'Cohérent':s==='PCIF_INSUFFICIENT'?'PCIF à compléter':'Non rapproché';
 return <article className="panel pcif"><div className="panel-title"><div><h3><ShieldCheck size={18}/> Maîtrise des risques · PCIF</h3><p>Le contrôle interne contextualise les signaux financiers sans se substituer au diagnostic.</p></div>{current?.uai&&onSync&&<button className="btn-soft" onClick={()=>onSync(current.uai!)} disabled={syncing}><RefreshCw size={15}/>{syncing?' Synchronisation…':' Actualiser'}</button>}</div>
 {!current?<p className="muted">Sélectionne un établissement pour afficher son contexte PCIF.</p>:p?<><div className="pcif-campaign"><b>{p.campaign_label||'Campagne PCIF'}</b>{p.campaign_status&&<span>{p.campaign_status==='DRAFT'?'Brouillon':p.campaign_status}</span>}</div>{answered===0?<div className="pcif-empty-data"><b>Diagnostic non renseigné</b><span>{total?`0 / ${total} points de contrôle évalués`:'Aucun point de contrôle évalué'}</span><small>La campagne existe mais ne contient pas encore de données permettant d'évaluer la maîtrise.</small></div>:<><div className="pcif-score"><b>{p.mastery_level!=null?`${Number(p.mastery_level).toFixed(0)} %`:'—'}</b><span>Maîtrise déclarée{trend!=null&&<em className={trend>=0?'up':'down'}>{trend>=0?<TrendingUp size={13}/>:<TrendingDown size={13}/>} {trend>0?'+':''}{trend} pt{Math.abs(trend)!==1?'s':''}</em>}</span></div><div className="pcif-progress"><div><span>Avancement du diagnostic</span><b>{completion} % · {answered}/{total}</b></div><progress max="100" value={completion}/></div><div className="pcif-mini"><span><b>{p.major_risks??0}</b> risques majeurs</span><span><b>{p.open_actions??0}</b> actions ouvertes</span><span><b>{p.overdue_actions??0}</b> en retard</span></div>{attention.length>0&&<div className="pcif-attention"><strong>Points d'attention</strong>{attention.map((a,i)=><div key={`${a.label}-${i}`}><span>{a.label}</span><b>{a.mastery!=null?`${a.mastery} %`:'—'}{a.majorRisks?` · ${a.majorRisks} risque${a.majorRisks>1?'s':''}`:''}</b></div>)}</div>}<div className="pcif-consistency"><div className="pcif-consistency-title"><strong>Cohérence avec les observations Vigie</strong>{reviews.length>0&&<span>{reviews.length} à examiner</span>}</div>{consistency.length===0?<small>Aucun signal Vigie rapprochable pour le moment.</small>:consistency.map((x,i)=><div className={`pcif-consistency-row ${x.status.toLowerCase()}`} key={`${x.vigieDomain}-${i}`}><span className="pcif-consistency-icon">{x.status==='REVIEW'?<AlertTriangle size={14}/>:x.status==='COHERENT'?<CheckCircle2 size={14}/>:<HelpCircle size={14}/>}</span><div><b>{x.vigieDomain}</b><small>{x.pcifDomain?`PCIF : ${x.pcifDomain}`:'Aucun domaine PCIF rapproché'} · {x.signals} signal{x.signals>1?'aux':''}</small><em>{x.reasons?.[0]}</em></div><strong>{statusLabel(x.status)}</strong></div>)}</div></>}<small>{p.campaign_label||'Campagne PCIF'} · actualisé {dateFr(p.updated_at)}</small>{p.source_url&&<a className="pcif-link" href={p.source_url} target="_blank" rel="noreferrer">Ouvrir dans PCIF Académie <ExternalLink size={14}/></a>}</>:<div className="empty-pcif"><ShieldCheck/><b>Contexte PCIF non connecté</b><span>{current.uai?`UAI ${current.uai} identifié. Vigie peut synchroniser la synthèse dès que l’API PCIF est configurée.`:'UAI non identifié : impossible de rapprocher automatiquement cet EPLE avec PCIF Académie.'}</span></div>}</article>
}
