import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ChevronDown, ChevronRight, Database, ReceiptText } from 'lucide-react';
import { api } from '../lib/api';
import type { Eple } from '../types/dashboard';
const eur=(n?:number|null)=>n==null?'—':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const pct=(n?:number|null)=>n==null?'—':new Intl.NumberFormat('fr-FR',{style:'percent',maximumFractionDigits:1}).format(n);
const Metric=({label,value,hint}:{label:string,value:any,hint?:string})=><div className="budget-kpi"><span>{label}</span><b>{value}</b>{hint&&<small>{hint}</small>}</div>;
function Bar({value}:{value:number}){return <div className="budget-bar"><i style={{width:`${Math.max(0,Math.min(100,value*100))}%`}}/></div>}
export function BudgetView({current}:{current:Eple|null}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState<'DEP'|'REC'>('DEP'),[open,setOpen]=useState<Set<string>>(new Set());
 useEffect(()=>{setData(null);setError('');if(!current?.opaleEntity)return;setLoading(true);api.budget(current.opaleEntity).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[current?.opaleEntity]);
 const services=useMemo(()=>data?.services?.filter((x:any)=>x.direction===tab)||[],[data,tab]),sum=tab==='DEP'?data?.summary?.expenses:data?.summary?.revenues;
 if(!current)return <div className="page"><div className="empty-domain"><Database size={34}/><span>BUDGET</span><h2>Sélectionne un établissement</h2><p>La lecture budgétaire est contextualisée par EPLE.</p></div></div>;
 if(loading)return <div className="page loading">Construction de l’explorateur budgétaire…</div>;
 if(error)return <div className="page"><div className="empty-domain"><AlertTriangle/><h2>Budget indisponible</h2><p>{error}</p></div></div>;
 if(!data?.snapshot)return <div className="page"><div className="empty-domain"><Database size={34}/><span>BUDGET</span><h2>Aucune situation budgétaire</h2><p>Importe l’export Budget Op@le au format .xlsx ou .lis pour {current.name}.</p></div></div>;
 const toggle=(k:string)=>setOpen(v=>{const n=new Set(v);n.has(k)?n.delete(k):n.add(k);return n});
 return <div className="page budget-page"><div className="budget-head"><div><span>BUDGET</span><h2><ReceiptText/> Explorateur budgétaire</h2><p>{current.name} · situation au {new Date(data.snapshot.date).toLocaleDateString('fr-FR')} · {data.snapshot.rowCount} lignes</p></div><div className="budget-tabs"><button className={tab==='DEP'?'active':''} onClick={()=>setTab('DEP')}>Dépenses</button><button className={tab==='REC'?'active':''} onClick={()=>setTab('REC')}>Recettes</button></div></div>
 <section className="budget-kpis"><Metric label={tab==='DEP'?'Budget dépenses':'Recettes prévues'} value={eur(sum?.budget)}/><Metric label={tab==='DEP'?'Engagé':'Engagé / constaté'} value={eur(sum?.committed)} hint={sum?.budget?pct(sum.committed/sum.budget):undefined}/><Metric label="Réalisé comptable" value={eur(sum?.accounted)}/><Metric label="En cours" value={eur(sum?.inProgress)}/><Metric label="Disponible" value={eur(sum?.available)}/></section>
 {data.signals?.length>0&&tab==='DEP'&&<section className="budget-attention"><b><AlertTriangle size={16}/> Points d’attention</b>{data.signals.slice(0,5).map((s:any)=><span key={s.service}><strong>{s.title}</strong> · {s.detail}</span>)}</section>}
 <section className="budget-table-wrap"><div className="budget-table-head"><div>Service / domaine / activité</div><div>Budget</div><div>Engagé</div><div>Réalisé</div><div>En cours</div><div>Disponible</div><div>Exécution</div></div>{services.map((s:any)=>{const k=s.code,o=open.has(k);return <div className="budget-group" key={k}><button className="budget-row service" onClick={()=>toggle(k)}><div>{o?<ChevronDown/>:<ChevronRight/>}<span><b>{s.code}</b><small>{s.label}</small></span></div><span>{eur(s.budget)}</span><span>{eur(s.committed)}</span><span>{eur(s.accounted)}</span><span>{eur(s.inProgress)}</span><span>{eur(s.available)}</span><span><b>{pct(s.rate)}</b><Bar value={s.rate||0}/></span></button>{o&&s.children.map((c:any)=>{const ck=`${k}/${c.code}`,co=open.has(ck);return <div key={ck}><button className="budget-row domain" onClick={()=>toggle(ck)}><div>{co?<ChevronDown/>:<ChevronRight/>}<span><b>{c.code}</b><small>{c.label}</small></span></div><span>{eur(c.budget)}</span><span>{eur(c.committed)}</span><span>{eur(c.accounted)}</span><span>{eur(c.inProgress)}</span><span>{eur(c.available)}</span><span>{c.budget?pct(c.committed/c.budget):'—'}</span></button>{co&&c.activities.map((a:any)=><div className="budget-row activity" key={`${ck}/${a.code}`}><div><i/>{a.code}</div><span>{eur(a.budget)}</span><span>{eur(a.committed)}</span><span>{eur(a.accounted)}</span><span>{eur(a.inProgress)}</span><span>{eur(a.available)}</span><span>{a.budget?pct(a.committed/a.budget):'—'}</span></div>)}</div>})}</div>})}{!services.length&&<div className="budget-empty">Aucune ligne {tab==='DEP'?'de dépense':'de recette'} identifiée dans cette situation.</div>}</section>
 <p className="budget-source">Source : {data.snapshot.filename}. Les taux sont des indicateurs de lecture ; ils ne constituent pas à eux seuls un diagnostic budgétaire.</p></div>
}
