import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ChevronDown, ChevronRight, Database, ReceiptText, Scale, Search, Table2 } from 'lucide-react';
import { api } from '../lib/api';
import type { Eple } from '../types/dashboard';
const eur=(n?:number|null)=>n==null?'—':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const eur2=(n?:number|null)=>n==null?'—':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const pct=(n?:number|null)=>n==null?'—':new Intl.NumberFormat('fr-FR',{style:'percent',maximumFractionDigits:1}).format(n);
const Metric=({label,value,hint}:{label:string,value:any,hint?:string})=><div className="budget-kpi"><span>{label}</span><b>{value}</b>{hint&&<small>{hint}</small>}</div>;
function Bar({value}:{value:number}){return <div className="budget-bar"><i style={{width:`${Math.max(0,Math.min(100,value*100))}%`}}/></div>}
const serviceName=(s:any)=>[s.code,s.label&&s.label!==s.code?s.label:null].filter(Boolean).join(' · ');
export function BudgetView({current}:{current:Eple|null}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[view,setView]=useState<'summary'|'analysis'|'structure'|'source'>('summary'),[tab,setTab]=useState<'DEP'|'REC'>('DEP'),[open,setOpen]=useState<Set<string>>(new Set()),[query,setQuery]=useState('');
 useEffect(()=>{setData(null);setError('');if(!current?.opaleEntity)return;setLoading(true);api.budget(current.opaleEntity).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[current?.opaleEntity]);
 const services=useMemo(()=>data?.services?.filter((x:any)=>x.direction===tab)||[],[data,tab]),sum=tab==='DEP'?data?.summary?.expenses:data?.summary?.revenues;
 if(!current)return <div className="page"><div className="empty-domain"><Database size={34}/><span>BUDGET</span><h2>Sélectionne un établissement</h2><p>La lecture budgétaire est contextualisée par EPLE.</p></div></div>;
 if(loading)return <div className="page loading">Construction de l’explorateur budgétaire…</div>;
 if(error)return <div className="page"><div className="empty-domain"><AlertTriangle/><h2>Budget indisponible</h2><p>{error}</p></div></div>;
 if(!data?.snapshot)return <div className="page"><div className="empty-domain"><Database size={34}/><span>BUDGET</span><h2>Aucune situation budgétaire</h2><p>Importe l’export Budget Op@le au format .xlsx ou .lis pour {current.name}.</p></div></div>;
 const toggle=(k:string)=>setOpen(v=>{const n=new Set(v);n.has(k)?n.delete(k):n.add(k);return n});
 const exp=data.totals?.expenses||data.summary?.expenses,rev=data.totals?.revenues||data.summary?.revenues,balance=(data.totals?.balance??((rev?.budget||0)-(exp?.budget||0))),need=Math.max(0,-balance);
 const Analysis=()=> <><section className="budget-kpis"><Metric label={tab==='DEP'?'Dépenses ouvertes':'Recettes prévues'} value={eur(sum?.budget)}/><Metric label={tab==='DEP'?'Engagé':'Constaté / engagé'} value={eur(sum?.committed)} hint={sum?.budget?pct(sum.committed/sum.budget):undefined}/><Metric label="Réalisé comptable" value={eur(sum?.accounted)}/><Metric label="En cours" value={eur(sum?.inProgress)}/><Metric label={tab==='DEP'?'Disponible':'Reste à réaliser'} value={eur(sum?.available)}/></section>{data.signals?.length>0&&tab==='DEP'&&<section className="budget-attention"><b><AlertTriangle size={16}/> Points d’attention</b>{data.signals.slice(0,5).map((s:any)=><span key={s.service}><strong>{s.title}</strong> · {s.detail}</span>)}</section>}<BudgetTree services={services} open={open} toggle={toggle}/></>;
 return <div className="page budget-page"><div className="budget-head"><div><span>BUDGET</span><h2><ReceiptText/> Explorateur budgétaire</h2><p>{current.name} · situation au {new Date(data.snapshot.date).toLocaleDateString('fr-FR')} · {data.snapshot.rowCount} lignes</p></div></div>
 <div className="budget-view-tabs"><button className={view==='summary'?'active':''} onClick={()=>setView('summary')}><Scale size={14}/>Synthèse</button><button className={view==='analysis'?'active':''} onClick={()=>setView('analysis')}>Analyse</button><button className={view==='structure'?'active':''} onClick={()=>setView('structure')}><Table2 size={14}/>Structure</button><button className={view==='source'?'active':''} onClick={()=>setView('source')}>Données sources</button></div>
 {view==='summary'&&<><section className="budget-global"><div><span>DÉPENSES OUVERTES</span><b>{eur(exp?.budget)}</b><small>{eur(exp?.accounted)} réalisées · {pct(exp?.budget?exp.accounted/exp.budget:null)}</small></div><div className="budget-balance"><span>{need>0?'BESOIN DE FINANCEMENT':'SOLDE PRÉVISIONNEL'}</span><b>{eur(Math.abs(balance))}</b><small>Recettes − dépenses : {eur(balance)}</small></div><div><span>RECETTES PRÉVUES</span><b>{eur(rev?.budget)}</b><small>{eur(rev?.accounted)} réalisées · {pct(rev?.budget?rev.accounted/rev.budget:null)}</small></div></section>
 <section className="budget-mirror"><div className="mirror-title dep">Dépenses</div><div className="mirror-center">Périmètre</div><div className="mirror-title rec">Recettes</div>{(data.scopes||[]).map((s:any)=><div className="mirror-row" key={s.code}><div className="mirror-side dep"><b>{eur2(s.expenses.budget)}</b><span>Réalisé {eur(s.expenses.accounted)} · {pct(s.expenses.budget?s.expenses.accounted/s.expenses.budget:null)}</span><Bar value={s.expenses.budget?s.expenses.accounted/s.expenses.budget:0}/></div><div className="mirror-scope"><b>{s.code}</b><span>{s.label}</span><em className={s.balance<0?'need':'surplus'}>{s.balance<0?`Besoin ${eur(Math.abs(s.balance))}`:`Excédent ${eur(s.balance)}`}</em></div><div className="mirror-side rec"><b>{eur2(s.revenues.budget)}</b><span>Réalisé {eur(s.revenues.accounted)} · {pct(s.revenues.budget?s.revenues.accounted/s.revenues.budget:null)}</span><Bar value={s.revenues.budget?s.revenues.accounted/s.revenues.budget:0}/></div></div>)}</section>
 <section className="budget-balance-table"><div><b>Total</b><strong>{eur(exp?.budget)}</strong><span>{eur(rev?.budget)}</span><em>{eur(balance)}</em></div><small>Les recettes Op@le sont normalisées en valeurs positives. Le solde affiché est « recettes − dépenses » : un montant négatif traduit un besoin de financement.</small></section></>}
 {view==='analysis'&&<><div className="budget-analysis-head"><div><h3>Analyse détaillée</h3><p>Une lecture pleine largeur adaptée à la nature de la donnée.</p></div><div className="budget-tabs"><button className={tab==='DEP'?'active':''} onClick={()=>setTab('DEP')}>Dépenses</button><button className={tab==='REC'?'active':''} onClick={()=>setTab('REC')}>Recettes</button></div></div><Analysis/></>}
 {view==='structure'&&<><div className="budget-analysis-head"><div><h3>Structure budgétaire</h3><p>Navigation service → domaine → activité, avec montants normalisés.</p></div><div className="budget-tabs"><button className={tab==='DEP'?'active':''} onClick={()=>setTab('DEP')}>Dépenses</button><button className={tab==='REC'?'active':''} onClick={()=>setTab('REC')}>Recettes</button></div></div><BudgetTree services={services} open={open} toggle={toggle}/></>}
 {view==='source'&&<SourceRows rows={data.sourceRows||[]} query={query} setQuery={setQuery}/>}<p className="budget-source">Source : {data.snapshot.filename}. Vigie conserve les valeurs brutes dans « Données sources » et normalise les signes pour les vues de gestion.</p></div>;
}
function BudgetTree({services,open,toggle}:{services:any[],open:Set<string>,toggle:(k:string)=>void}){return <section className="budget-table-wrap"><div className="budget-table-head"><div>Service / domaine / activité</div><div>Budget</div><div>Engagé</div><div>Réalisé</div><div>En cours</div><div>Disponible</div><div>Exécution</div></div>{services.map((s:any)=>{const k=s.code,o=open.has(k);return <div className="budget-group" key={k}><button className="budget-row service" onClick={()=>toggle(k)}><div>{o?<ChevronDown/>:<ChevronRight/>}<span><b>{s.code}</b><small>{s.label}</small></span></div><span>{eur(s.budget)}</span><span>{eur(s.committed)}</span><span>{eur(s.accounted)}</span><span>{eur(s.inProgress)}</span><span>{eur(s.available)}</span><span><b>{pct(s.rate)}</b><Bar value={s.rate||0}/></span></button>{o&&s.children.map((c:any)=>{const ck=`${k}/${c.code}`,co=open.has(ck);return <div key={ck}><button className="budget-row domain" onClick={()=>toggle(ck)}><div>{co?<ChevronDown/>:<ChevronRight/>}<span><b>{c.code}</b><small>{c.label}</small></span></div><span>{eur(c.budget)}</span><span>{eur(c.committed)}</span><span>{eur(c.accounted)}</span><span>{eur(c.inProgress)}</span><span>{eur(c.available)}</span><span>{c.budget?pct(c.committed/c.budget):'—'}</span></button>{co&&c.activities.map((a:any)=><div className="budget-row activity" key={`${ck}/${a.code}`}><div><i/>{a.code}</div><span>{eur(a.budget)}</span><span>{eur(a.committed)}</span><span>{eur(a.accounted)}</span><span>{eur(a.inProgress)}</span><span>{eur(a.available)}</span><span>{a.budget?pct(a.committed/a.budget):'—'}</span></div>)}</div>})}</div>})}{!services.length&&<div className="budget-empty">Aucune ligne identifiée dans cette situation.</div>}</section>}
function SourceRows({rows,query,setQuery}:{rows:any[],query:string,setQuery:(v:string)=>void}){const q=query.trim().toLowerCase(),filtered=q?rows.filter((r:any)=>JSON.stringify(r).toLowerCase().includes(q)):rows;return <section className="budget-source-view"><div className="source-toolbar"><div><h3>Données sources Op@le</h3><p>Valeurs brutes importées, signes Op@le conservés.</p></div><label><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Compte, CGR, poste…"/></label></div><div className="source-table"><div className="source-row head"><span>Ligne</span><span>Sens</span><span>CGR</span><span>Compte</span><span>Budget brut</span><span>Réalisé brut</span></div>{filtered.slice(0,500).map((r:any)=><div className="source-row" key={r.lineNo}><span>{r.lineNo}</span><span>{r.direction}</span><span>{r.cgr?.map((x:any)=>x.code).filter(Boolean).join(' › ')}</span><span>{r.account||'—'}</span><span>{eur2(r.budget)}</span><span>{eur2(r.accounted)}</span></div>)}</div>{filtered.length>500&&<p className="budget-source">500 lignes affichées sur {filtered.length}. Utilise la recherche pour affiner.</p>}</section>}
