import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CalendarDays, Coins, Info, Landmark, ReceiptText, Target, TrendingUp, ChevronRight, X } from 'lucide-react';
import { eur, pct } from '../lib/format';
import type { Dashboard, Eple } from '../types/dashboard';
import { PcifCard } from '../components/PcifCard';
import { SignalCard } from '../components/SignalCard';
import { TrajectoryChart } from '../components/TrajectoryChart';

type LandingAssumptions={placements:number;expectedReceipts:number;expectedPayments:number;futureProducts:number;futureCharges:number};
type FinancialContext={balance?:{result?:number|null}|null};
const EMPTY_ASSUMPTIONS:LandingAssumptions={placements:0,expectedReceipts:0,expectedPayments:0,futureProducts:0,futureCharges:0};
function Kpi({icon,label,value,hint,delta,className}:any){return <article className={`kpi ${className||''}`}><div className="kpi-head">{icon}<span>{label}</span></div><b>{value}</b><small>{hint}</small>{delta!=null&&<em className={delta<0?'down':'up'}>{delta<0?'↓':'↑'} {eur(Math.abs(delta))}</em>}</article>}
function Row({n,v,strong}:any){return <div className={strong?'strong':''}><span>{n}</span><b>{v}</b></div>}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0}
export function HomeView({dash,current,openSignal,setOpenSignal,onPcifSync,pcifSyncing}:{dash:Dashboard;current:Eple|null;openSignal:string|null;setOpenSignal:(v:string|null)=>void;onPcifSync?:(uai:string)=>void;pcifSyncing?:boolean}){
 const signals=current?.signals||dash.signals||[],m=current?.budgetMetrics,fdr=current?.fdrHistory?.[0],prev=current?.fdrHistory?.[1],agency=!current;
 const fdrDelta=fdr&&prev?Number(fdr.amount)-Number(prev.amount):null;
 const trajectory=signals.some(s=>s.level==='alert')?'Action requise':signals.some(s=>s.level==='watch')?'À surveiller':'Trajectoire maîtrisée';
 const [financial,setFinancial]=useState<FinancialContext|null>(null),[landingOpen,setLandingOpen]=useState(false),[assumptions,setAssumptions]=useState<LandingAssumptions>(EMPTY_ASSUMPTIONS);
 useEffect(()=>{setFinancial(null);if(!current)return;fetch(`/api/financial/${encodeURIComponent(current.id)}`).then(r=>r.ok?r.json():null).then(setFinancial).catch(()=>setFinancial(null))},[current?.id]);
 useEffect(()=>{if(!current){setAssumptions(EMPTY_ASSUMPTIONS);return}try{const raw=localStorage.getItem(`vigie:landing:${current.id}:${new Date().getFullYear()}`);setAssumptions(raw?{...EMPTY_ASSUMPTIONS,...JSON.parse(raw)}:EMPTY_ASSUMPTIONS)}catch{setAssumptions(EMPTY_ASSUMPTIONS)}},[current?.id]);
 const saveAssumptions=(next:LandingAssumptions)=>{setAssumptions(next);if(current)localStorage.setItem(`vigie:landing:${current.id}:${new Date().getFullYear()}`,JSON.stringify(next))};
 const treasuryKnown=current?.treasury?.currentBalance!=null,currentTreasury=n(current?.treasury?.currentBalance),resultKnown=financial?.balance?.result!=null,currentResult=n(financial?.balance?.result);
 const projectedTreasury=treasuryKnown?currentTreasury+assumptions.placements+assumptions.expectedReceipts-assumptions.expectedPayments:null;
 const projectedResult=resultKnown?currentResult+assumptions.futureProducts-assumptions.futureCharges:null;
 const projectionInputs=[assumptions.expectedReceipts,assumptions.expectedPayments,assumptions.futureProducts,assumptions.futureCharges].filter(x=>x!==0).length;
 const projectionConfidence=projectionInputs>=4?'Hypothèses renseignées':projectionInputs>=2?'Projection partielle':'Projection à compléter';
 const resultHint=projectedResult!=null?`Au 31/12 · ${projectionConfidence.toLowerCase()}`:'Importer une EBLC pour amorcer la projection';
 return <div className="home fade-in"><section className="hero-kpis"><article className={'trajectory '+(trajectory==='Action requise'?'danger':'')}><Target/><span>Trajectoire globale</span><b>{trajectory}</b><small>{agency?'Lecture consolidée de l’agence':current.name}</small></article><Kpi className={!agency?'treasury-live':''} icon={<Coins/>} label={agency?'Budget disponible':'Trésorerie projetée'} value={agency?eur(dash.kpis.totalAvailable):projectedTreasury!=null?eur(projectedTreasury):'À connecter'} hint={agency?'Derniers budgets importés':projectedTreasury!=null?`au 31/12 · ${projectionConfidence.toLowerCase()}`:'5151 + hypothèses à intégrer'}/><Kpi icon={<Landmark/>} label="Fonds de roulement" value={fdr?eur(fdr.amount):'—'} hint={fdr?`${fdr.exercise} · ${fdr.is_final?'définitif':'provisoire'}`:'FDR non importé'} delta={fdrDelta}/><Kpi icon={<TrendingUp/>} label="Résultat prévisionnel" value={agency?'—':projectedResult!=null?eur(projectedResult):'À construire'} hint={agency?'Sélectionner un établissement':resultHint}/><Kpi icon={<ReceiptText/>} label="Engagement budgétaire" value={m?pct(m.engagementRate):agency&&dash.kpis.totalBudget?pct(Number(dash.kpis.totalCommitted||0)/Number(dash.kpis.totalBudget)):'—'} hint={m&&m.trajectoryTarget?`Cible à date ≈ ${pct(m.trajectoryTarget)}`:'Engagé / montant évaluatif'}/></section>
 <section className="main-grid"><article className="panel execution"><div className="panel-title"><div><h3>Exécution budgétaire</h3><p>Engagement réel comparé à la trajectoire EPLE.</p></div><span className="pill">Engagement</span></div><TrajectoryChart rate={m?.engagementRate} target={m?.trajectoryTarget}/>{m?<div className="metric-row"><span><b>{eur(m.budget)}</b> montant évaluatif</span><span><b>{eur(m.committed)}</b> engagé</span><span><b>{eur(m.accounted)}</b> dont réalisé</span><span><b>{eur(m.available)}</b> disponible</span></div>:<p className="muted">Sélectionne un établissement pour détailler sa trajectoire.</p>}</article>
 <article className={`panel landing ${current?'landing-live':''}`}><div className="panel-title"><div><h3>Trésorerie et atterrissage</h3><p>Constaté, identifié, attendu, estimé.</p></div><Info size={16}/></div><div className="landing-list"><Row n="Solde 5151 constaté" v={treasuryKnown?eur(currentTreasury):'À connecter'}/><Row n="Placements (CAT)" v={assumptions.placements?eur(assumptions.placements):'À renseigner'}/><Row n="Encaissements attendus" v={assumptions.expectedReceipts?eur(assumptions.expectedReceipts):'À renseigner'}/><Row n="Décaissements prévus" v={assumptions.expectedPayments?eur(assumptions.expectedPayments):'À renseigner'}/><Row n="Trésorerie projetée au 31/12" v={projectedTreasury!=null?eur(projectedTreasury):'—'} strong/><Row n="Résultat prévisionnel" v={projectedResult!=null?eur(projectedResult):'—'} strong/></div><button className="detail-link" disabled={!current} onClick={()=>setLandingOpen(true)}>Construire l'atterrissage au 31/12 <ChevronRight size={15}/></button></article>
 <article className="panel priorities"><div className="panel-title"><div><h3><AlertTriangle size={18}/> Signaux prioritaires</h3><p>{signals.length} signal(s) sur le périmètre.</p></div></div>{signals.slice(0,6).map((s,i)=>{const key=`${s.code}-${i}`;return <SignalCard key={key} signal={s} open={openSignal===key} onToggle={()=>setOpenSignal(openSignal===key?null:key)}/>})}</article></section>
 <section className="lower-grid"><article className="panel calendar"><div className="panel-title"><div><h3><CalendarDays size={18}/> Calendrier de gestion</h3><p>La trajectoire tient compte du rythme réel d'un EPLE.</p></div></div><div className="months">{['Jan.','Fév.','Mars','Avr.','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'].map(x=><span key={x}>{x}</span>)}</div><div className="phases"><div className="p1">1. Mise en route<small>Exécution calme</small></div><div className="p2">2. Préparation de la rentrée<small>Objectif 75–80 % au 31/08</small></div><div className="summer">Fermeture estivale<small>Activité réduite</small></div><div className="p3">3. Atterrissage<small>Derniers engagements</small></div><div className="closep">Clôture<small>Solde et régularisations</small></div></div></article><PcifCard current={current} onSync={onPcifSync} syncing={pcifSyncing}/></section>
 {landingOpen&&current&&<div className="modalveil" onMouseDown={e=>{if(e.currentTarget===e.target)setLandingOpen(false)}}><section className="landing-modal"><button className="landing-close" onClick={()=>setLandingOpen(false)} aria-label="Fermer"><X size={18}/></button><span className="eyebrow">ATTERRISSAGE · {current.name}</span><h2>Projection au 31/12</h2><p>Vigie part des données constatées et te laisse compléter uniquement les flux futurs qu'OP@LE ne peut pas connaître.</p><div className="landing-form"><fieldset><legend>Trésorerie</legend><label>5151 constaté <b>{treasuryKnown?eur(currentTreasury):'Non disponible'}</b></label><MoneyInput label="Placements / CAT" value={assumptions.placements} onChange={v=>saveAssumptions({...assumptions,placements:v})}/><MoneyInput label="Encaissements attendus" value={assumptions.expectedReceipts} onChange={v=>saveAssumptions({...assumptions,expectedReceipts:v})}/><MoneyInput label="Décaissements prévus" value={assumptions.expectedPayments} onChange={v=>saveAssumptions({...assumptions,expectedPayments:v})}/><div className="landing-total"><span>Trésorerie projetée</span><b>{projectedTreasury!=null?eur(projectedTreasury):'—'}</b></div></fieldset><fieldset><legend>Résultat</legend><label>Résultat comptable à date <b>{resultKnown?eur(currentResult):'EBLC requise'}</b></label><MoneyInput label="Produits restant à réaliser" value={assumptions.futureProducts} onChange={v=>saveAssumptions({...assumptions,futureProducts:v})}/><MoneyInput label="Charges restant à réaliser" value={assumptions.futureCharges} onChange={v=>saveAssumptions({...assumptions,futureCharges:v})}/><div className="landing-total"><span>Résultat prévisionnel</span><b>{projectedResult!=null?eur(projectedResult):'—'}</b></div></fieldset></div><div className="landing-method"><b>Méthode</b><span>Trésorerie 31/12 = 5151 constaté + placements + encaissements attendus − décaissements prévus.</span><span>Résultat prévisionnel = résultat comptable à date + produits restant à réaliser − charges restant à réaliser.</span><small>{projectionConfidence}. Les hypothèses sont enregistrées localement pour cet établissement et cet exercice.</small></div></section></div>}
 </div>
}
function MoneyInput({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="money-input"><span>{label}</span><div><input type="number" step="100" value={value||''} placeholder="0" onChange={e=>onChange(n(e.target.value))}/><i>€</i></div></label>}
